// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nibo.Data.Context;

namespace Nibo.Data.Migrations
{
    [DbContext(typeof(MeuDbContext))]
    [Migration("20200613171906_inicio")]
    partial class inicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Nibo.Business.Models.BankStatement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnName("NAME")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("StatementEnd")
                        .HasColumnName("DTEND")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("StatementStart")
                        .HasColumnName("DTSTART")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("BankStatements");
                });

            modelBuilder.Entity("Nibo.Business.Models.SignOn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SIGONID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateServer")
                        .HasColumnName("DTSERVER")
                        .HasColumnType("datetime");

                    b.Property<string>("Language")
                        .HasColumnName("LANGUAGE")
                        .HasColumnType("varchar(3)");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StatusCode");

                    b.ToTable("SignOn");
                });

            modelBuilder.Entity("Nibo.Business.Models.Status", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CODE")
                        .HasColumnType("integer")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Severity")
                        .HasColumnName("SEVERITY")
                        .HasColumnType("VARCHAR(5)");

                    b.HasKey("Code");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("Nibo.Business.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnName("TRNAMT")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("BankStatementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Memo")
                        .HasColumnName("MEMO")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("TransactionPostDate")
                        .HasColumnName("DTPOSTED")
                        .HasColumnType("datetime");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnName("TRNTYPE")
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("BankStatementId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Nibo.Business.Models.SignOn", b =>
                {
                    b.HasOne("Nibo.Business.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusCode");
                });

            modelBuilder.Entity("Nibo.Business.Models.Transaction", b =>
                {
                    b.HasOne("Nibo.Business.Models.BankStatement", "BankStatement")
                        .WithMany("Transactions")
                        .HasForeignKey("BankStatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
